---
apiVersion: v2
appVersion: v3.8.0
description: A developer-oriented health dashboard that gives you the ability to monitor your services using HTTP, ICMP, TCP, and even DNS queries.
icon: https://github.com/TwiN/gatus/raw/master/.github/assets/logo-with-dark-text.png
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/gatus
name: gatus
version: 1.1.2
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/TwiN/gatus
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: oci://ghcr.io/elfhosted/charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
