{{ if .Values.knightcrawlervpn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: knightcrawler-vpn
  labels:
    app.kubernetes.io/name: knightcrawlervpn
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 7001
    targetPort: 7001
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: knightcrawlervpn
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}