{{ if .Values.torrentio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: torrentio
  labels:
    app.kubernetes.io/name: torrentio
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 7001
    targetPort: 7001
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: torrentio
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}