{{ if .Values.knightcrawler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: knightcrawler
  labels:
    app.kubernetes.io/name: knightcrawler
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: knightcrawler
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}