---
apiVersion: v2
appVersion: 1.30.1
description: Unpacks archives
name: overseerr
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - unpackerr
home: https://github.com/sct/overseerr
icon: https://avatars.githubusercontent.com/u/14336958?s=200&v=4
sources:
  - https://github.com/sct/overseerr
maintainers:
  - name: funkypenguin
    email: davidy@funkypenguin.co.nz
dependencies:
  - name: common
    repository: oci://ghcr.io/elfhosted/charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
