{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "torrentio-env",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "torrentio-env",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgCIERiSEh6gY0mIVTg0k2U4IwL8s6hihFeIiuVi5OM8TJ91il7AvFS/77ZjuOe5a2tJsvFOtN6wZQYzkYNi5rFBuxQPBEu01xW+jBdIN+ZXMlKpKWQ/tcDxpfW2ShDHh6AdZSlyc1rswmgoVh0reRBYBd534+f1/1oF0H5FsonnFw5eqvU3qUzHwTn53RlSDDEVQt4xsz6MfsYwuUnEKpHS1Sf1HQPt+dCEZohwbpXvzxEB1C87YGODt/5eoJT4oGDegoCpp3FXqBPQ/tjOMAqkM6PngemqPTA2tqJq4ZNxDPzTHepKS9jM67uQgBvtCbLEUlXu8lUoC69rGTpWls+0MXUru73MfWEu/OT1VaJlmmpvJ3vqwHloj4v+x3AmY0632u4VdZZS0E5RtgbZEdMMnuhRzURVc7myuQ6Ead9DMCZEyh8obDJ+FQdGcx3x7mK3kFX5Y6M5acMRQgXQ+TPR6t9zQBd4hH6LbZtBO01DTSdi8aoquj7yu/Oev+J/nrRwKRprockyPdYboWBZFFUQbRVjYAJoqK692k/rNpKKeCw38z1tgHCuWsjTN6YE/7jJpYd1S4ZSgioaTvfMuToPTGIBAXJKZR9m9DfVSjfJ/2HvWzHeaL0XNqhuMj9XwrPVmR5XKGi4SHnoEz5qekIsN+yoYhTXHE4V1ZZxawQh4n0cDeoHy9oX2tg4TfcJgGHWQewXdWWZ1VXaT3CKJqeI9q45or5S"
    }
  }
}
