---
apiVersion: v2
appVersion: 0.4.4
description: Client for notifiarr.com
name: notifiarr
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - xteve
  - iptv
  - plex
  - emby
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/xteve
icon: https://raw.githubusercontent.com/xteve-project/xTeVe/master/html/img/logo_b_880x200.jpg
sources:
  - https://github.com/xteve-project/xTeVe
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: oci://ghcr.io/elfhosted/charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
