---
apiVersion: v2
appVersion: v4.4.2
description: qBittorrent is a cross-platform free and open-source BitTorrent client
name: qbittorrent
version: 13.5.6
kubeVersion: ">=1.16.0-0"
keywords:
  - qbittorrent
  - torrrent
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/qbittorrent
icon: https://cloud.githubusercontent.com/assets/14862437/23586868/89ef2922-01c4-11e7-869c-52aafcece17f.png
sources:
  - https://github.com/qbittorrent/qBittorrent
  - https://github.com/k8s-at-home/container-images
maintainers:
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: common
    repository: oci://ghcr.io/elfhosted/charts
    version: ~0.2.10
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 0.2.2
